<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="BHAVNAWKS093" name="com.qa.test.CreditCard" tests="3" failures="0" timestamp="1 May 2019 07:39:26 GMT" time="0.001" errors="1">
  <testcase name="fillCreditCardForm" time="0.001" classname="com.qa.test.CreditCard">
    <skipped/>
  </testcase> <!-- fillCreditCardForm -->
  <testcase name="prepareSetUp" time="0.000" classname="com.qa.test.CreditCard">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qa.test.BaseClass.launchApp(BaseClass.java:81)
	at com.qa.test.BaseClass.prepareSetUp(BaseClass.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- prepareSetUp -->
  <testcase name="sendDocumentSupportRequest" time="0.000" classname="com.qa.test.CreditCard">
    <skipped/>
  </testcase> <!-- sendDocumentSupportRequest -->
</testsuite> <!-- com.qa.test.CreditCard -->
